catch throwable instead of exception in case of NoClassDefFoundError (#103)
if any of the depending jar's are missing, an NoClassDefFoundError will be throw in the event of processing. catch throwable instead of exception.